spring:
  application:
    name: seok

  data:
    redis:
#      host: redis
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    hibernate:
      # 로컬 실습 환경이므로 스프링이 켜질 때 Entity 클래스를 읽어 테이블을 자동으로 만들거나 수정하도록 설정
      ddl-auto: update
    properties:
      hibernate:
        # 콘솔창에 JPA가 날리는 SQL 쿼리문을 이쁘게 출력해주는 데브옵스 디버깅용 옵션
        show_sql: true
        format_sql: true
        use_sql_comments: true

management:
  endpoints:
    web:
      exposure:
        # 외부로 노출할 액츄에이터 엔드포인트를 지정, 프로메테우스용 수집 경로, 애플리케이션 상태 체크 경로
        include: "health, prometheus"
  endpoint:
    health:
      # health 체크 시 상세한 상태 정보(디스크, DB 연결 등)를 보여줌
      show-details: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html